export const GET_QUERIES = "GET_QUERIES";
export const GET_QUERY = "GET_QUERY";
export const CREATE_QUERY = "CREATE_QUERY";
export const UPDATE_QUERY = "UPDATE_QUERY";
export const DELETE_QUERY = "DELETE_QUERY";
export const SET_REQUEST_STATUS_PENDING = "SET_REQUEST_STATUS_PENDING";
export const SET_REQUEST_STATUS_SUCCESS = "SET_REQUEST_STATUS_SUCCESS";
export const SET_REQUEST_STATUS_FAILURE = "SET_REQUEST_STATUS_FAILURE";

export const SET_FILTER_NAME = "SET_FILTER_NAME";
export const SET_FILTER_CREATOR = "SET_FILTER_CREATOR";
export const SET_FILTER_DESCRIPTION = "SET_FILTER_DESCRIPTION";
